version: "3.1"

services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9040:10084
    environment:
      VIRTUAL_HOST: w2api.cartesiancs.com
      LETSENCRYPT_HOST: w2api.cartesiancs.com
      LETSENCRYPT_EMAIL: hhj@devent.kr
    network_mode: "bridge"
