version: "3.1"

services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9040:10083
    environment:
      VIRTUAL_HOST: https://w2api.cartesiancs.com/
      LETSENCRYPT_HOST: https://w2api.cartesiancs.com/
      LETSENCRYPT_EMAIL: hhj@devent.kr
    network_mode: "bridge"
